# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmlBvUIhoQs03IXtcRZCR2qN0C70kZ_N

Import libraries
"""

import math
import pandas as pd
import matplotlib.pyplot as plt

"""Create dataset"""

# Dataset
data = [
    (2, 4, "Negative"),
    (4, 6, "Negative"),
    (4, 4, "Positive"),
    (4, 2, "Negative"),
    (6, 4, "Negative"),
    (6, 2, "Positive")
]

# Convert to DataFrame for better view
df = pd.DataFrame(data, columns=["S1", "S2", "Class"])
print("Dataset:\n", df)

# Target point
point = (6, 6)
k = 3

# Step 1: Calculate Euclidean distance
df["Distance"] = df.apply(lambda row: math.sqrt((point[0]-row["S1"])**2 + (point[1]-row["S2"])**2), axis=1)
print("\nDataset with distances:\n", df)

# Step 2: Sort by distance
df_sorted = df.sort_values(by="Distance")
print("\nDataset sorted by distance:\n", df_sorted)

# Step 3: Pick k nearest neighbors
neighbors = df_sorted.head(k)
print("\nNearest Neighbors:\n", neighbors)

# Step 4: Majority voting
predicted_class = neighbors["Class"].mode()[0]

print("\nNearest Neighbors:\n", neighbors)
print("\nPredicted Class for", point, ":", predicted_class)

# ---------------- Visualization ---------------- #
plt.figure(figsize=(8,6))

# Plot all points by class
for cls, color in zip(["Positive", "Negative"], ["green", "red"]):
    subset = df[df["Class"]==cls]
    plt.scatter(subset["S1"], subset["S2"], c=color, label=cls, s=100)

# Highlight nearest neighbors with a black edge
plt.scatter(neighbors["S1"], neighbors["S2"], facecolors='none', edgecolors='black', s=200, linewidths=2, label='Nearest Neighbors')

# Plot the test point
plt.scatter(point[0], point[1], c='blue', marker='X', s=200, label=f'Test Point ({predicted_class})')

# Labels, title, and legend
plt.xlabel("S1")
plt.ylabel("S2")
plt.title("k-NN Classification (k=3)")
plt.legend()
plt.grid(True)
plt.show()